### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by GJ-JG** [GJ-JG/hello-world#2]
- learn something about github remote and local.
- [x] how to sync remote and local
- [x] how to prevent input user name and password every time does git push
- [x] how to sync remote git with IntelliJ
- [x] what is git fork
